@startuml

left to right direction

actor Visualizador
actor Contribuyente
actor Administrador as Administrador
Contribuyente --|> Visualizador
Administrador --|> Contribuyente

rectangle "MetaMapa" {

    usecase "Iniciar sesión" as UC_Login

    usecase "Ver hechos de colección" as UC_VerHechos
    usecase "Crear hecho" as UC_CrearHecho
    usecase "Solicitar eliminación" as UC_SolicitarEliminacion
    usecase "Importar hechos" as UC_Importar
    usecase "Leer archivo CSV" as UC_LeerCSV
    usecase "Aceptar solicitud de eliminación" as UC_Aceptar
    usecase "Rechazar solicitud de eliminación" as UC_Rechazar
}

Visualizador --> UC_VerHechos


Contribuyente --> UC_Login

Contribuyente --> UC_CrearHecho
Contribuyente --> UC_SolicitarEliminacion

Administrador --> UC_Importar
Administrador --> UC_Aceptar
Administrador --> UC_Rechazar

UC_Importar --> UC_LeerCSV : <<include>>

@enduml