@startuml

class Visualizador

class Contribuyente extends Visualizador{
    - String nombre
    - String apellido
    - Interger edad
    + void crearHecho(titulo, descripcion, latitud, longitud, fechaAcontecimiento)
    + void solicitarEliminacionDeHecho(Hecho hecho)
}

class Administrador extends Contribuyente{
    - List<Coleccion> MisColecciones
    + void crearColeccion(String titulo, String descripcion)
    + void importHechosDesdeArchivo(Coleccion coleccion)
    + void aceptarSolicitud(Solicitud solicitud)
    + void rechazarSolicitud(Solicitud solicitud)
    + void etiquetarhecho(Hecho hecho)
}

class Hecho{
    - Boolean oculto
    - String titulo
    - String descripcion
    - String categoria
    - Etiqueta etiqueta
    - Ubicacion CoordenadasDelHecho
    - DateTime fechaAcontecimiento
    - DateTime fechaCarga
    - Origen OrigenHecho
}
class HechoMultimedia extends Hecho{
    - String Multimedia
}

class Ubicacion{
    - float latitud
    - float longitud
}

class Coleccion{
    - String titulo
    - String descripcion
    - FuenteEstatica fuente
    - List<Hecho> hechos
    - List<CriterioDePertenencia> criteriosDepertenencia
    + List<Hecho> buscarHechosConFiltros(List<Filtros>)
    + List<Hecho> importarCvg(List<CriterioDePertenencia>)
    + void agregarHecho(Hecho)
    + void quitarHecho(Hecho)
    + void agregarCriterio(CriterioDePertenencia)
    + void quitarCriterio(CriterioDePertenencia)
}

 interface Fuente <<interface>>{
    + List<Hecho> obtenerHechos()
}

 class FuenteEstatica implements Fuente{
    - String ubicacionDelArchivo
    + List<Hecho> obtenerHechos()
}

 class FuenteDinamica implements Fuente{
    + List<Hecho> obtenerHechos()
}

 class FuenteProxy implements Fuente{
    + List<Hecho> obtenerHechos()
}

interface CriterioDePertenencia{
    + Boolean evaluarCriterio()
}

class CriterioCategoria implements  CriterioDePertenencia{
    + Boolean evaluarCriterio(Hecho hecho)
}

class CriterioRangoFechaHora implements  CriterioDePertenencia{
    + Boolean evaluarCriterio(Hecho hecho)
}

class Criterioubicacion implements  CriterioDePertenencia{
    + Boolean evaluarCriterio(Hecho hecho)
}

class SolicitudDeEliminacion{
    - Hecho hecho
    - String motivo
    - Estado estado
}

enum Estado{
    PENDIENTE
    ACEPTADO
}

Coleccion *-- CriterioDePertenencia
Coleccion --> Fuente
Coleccion --> Hecho
Hecho --> Origen
Hecho *-- Ubicacion
Fuente ..> Hecho
SolicitudDeEliminacion --> Hecho
SolicitudDeEliminacion --> Estado
SolicitudDeEliminacion <.. Contribuyente

@enduml